### PR TITLE
Navigation improvements

### PR DESCRIPTION
**Pull request by marcelblum**
some navigational niceties to improve docs readability (IMHO):

1. scroll sidebar to selected target anchor when in desktop view
2. class index properties and methods sections separate own props & methods from inherited ones (perhaps more could be done in this regard but it's a start, my aim was to highlight props unique to each class to make it easier for readers to quickly identify the more relevant props)
3. back to top button

### CODE REVIEW

**Comment by tambien** [comment]
Thank you for the Pull Request. The back to top and sidebar scrollIntoView are perfect! 

I also completely understand the need to declutter the docs from the inherited methods, but i wonder if there's a more clear way to do this. I had actually tried hiding a lot of methods in the [previous version of the docs](https://tonejs.github.io/docs/13.8.25/Freeverb) to try and remove as much clutter as i could, but had a number of people also tell me this was confusing when they were looking for a method documentation which should be on the class. 

Going by inheritance alone might not be the right approach. There are some classes whose entire functionality is inherited like Amplitude Envelope for example. So the docs in this case wouldn't declutter the important members/methods such as `attack`, `decay`, `triggerAttack`, etc. from the unimportant ones like `now`, `toString()`. 

image

In this case i feel like separating 'own' from 'inherited' is more confusing than seeing them in a flat list because it also requires that the reader understand some implementation details (the class hierarchy inherits a lot from Envelope) which are not necessarily relevant for understanding the class. 

I guess my ideal solution would be to sort the class index by the level of inheritance, for example methods on AmplitudeEnvelope inherited from Envelope would be above methods inherited from ToneWithContext. I think this would be more understandable than a binary split of "own" vs "inherited". 

If this is something you'd like to take on, i would still merge the sidebar and back to top changes, if you would remove the alterations to the class index structure. You could move the index structure change to another PR.

**Comment by marcelblum** [comment]
Ok I reverted the class index changes for now, will think about it some more. The challenge is to find a catch-all solution that does more good than harm, without unintended consequences of making the docs more confusing :)

I'm thinking the ideal might be to create some kind of internal list of uber base classes to categorize as e.g. "other inherited props" at the bottom, while separating out "own" and "inherited from [relevant parent class]" sections above. That might elevate some less important props to the top like "name" but still (hopefully?) improve things overall. The "other" category could include e.g. ToneAudioNode.*, ToneWithContext.*, Tone.*. Something like:

### Properties
**Own**
- input
- name
- output

**Inherited from Envelope**
- attack
- attackCurve
- decay
- decayCurve
- release
- releaseCurve
- sustain
- value

**Other inherited properties**
- blockTime
- channelCount
- channelCountMode
- channelInterpretation
- context
- debug
- disposed
- numberOfInputs
- numberOfOutputs
- sampleTime
- version

### Methods
**Own**
- dispose

**Inherited from Envelope**
- asArray 
- cancel 
- connect 
- getDefaults
- getValueAtTime 
- triggerAttack 
- triggerAttackRelease 
- triggerRelease 

**Other inherited methods**
- chain
- disconnect
- fan
- get
- immediate
- now
- set
- toDestination
- toFrequency
- toMaster
- toSeconds
- toString
- toTicks

**Comment by tambien** [comment]
I like the idea of having an "other" category and treating those differently. maybe the UI could also be a little subtler, like instead of adding a new subheading for "own" and "other", maybe just the color of the item in the list could be dark gray which would make all of the colorful items in the index pop out. 

thanks for taking the time to try and improve the docs! very helpful for all of the Tone.js users.

**Comment by marcelblum** [comment]
Happy to continue to chip away at this especially now that I'm more familiar with how the docs are built so future changes will be easy. I'm still learning to use Tone itself and spending a lot of time wading through the docs.

Can you clarify what you're proposing? Are you saying you'd like the parent class names to be basically a grey item within the list, instead of a heading on a line of its own? That should work nicely, just want to make sure I'm understanding.

**Comment by marcelblum** [comment]
Something like this?
Screenshot_2020-09-14 AmplitudeEnvelope(1)

**Comment by tambien** [comment]
I was actually thinking of not including all of those sub-headers since they seem to clutter things IMO. 

image

Or similarly, could just use an underline to show which are the most relevant properties

image

**Comment by tambien** [comment]
I think it'd be similarly helpful if all of those properties/methods were at the beginning of the index (and also underlined) so it was clear what the most important information is. 

image

The members/methods definitions should be sorted in the same way.

**Comment by marcelblum** [comment]
Ok. I defer to whatever you think is best as BDFL of Tone. I think it just becomes an issue of sorting here. To me as a learner of the lib reading the docs I definitely found it unhelpful how all the props were sorted alphabetically with no regard to their importance to the specific class. So I agree with your latest image to discard the alphabetic sorting in the index. But the question remains how to sort those "important" props at the front of the list. In your image you have the "inherited from Envelope" props at the top of the list but "own" props mixed in with the "others". I think that would be a mistake because sometimes the most important props are "own", for example in `Distortion` or `BitCrusher`. Do you approve of combining "own" and "important inherited props" underlined & at the top of the list, with "others" at the bottom of the list and not underlined? If so, do we alphabetize that subset list at the top? Or list "own" first, followed by "important" inherited, followed by "others"?

**Comment by marcelblum** [comment]
Thinking about this some more, one way we could further declutter a potential "own" sub-subsection of the subset "important" list would be to exclude any read-only properties from the top and dump those in with the "others" at the bottom. I'm thinking that would help deemphasize stuff like `type`, `baseType`, `name` etc. Or if this would have bad unintended consequences I'm not foreseeing let me know.

Also, as a Tone learner interested in both the library itself as well as it's source and how it's structured, I would find it useful to know the parent classes at a glance when browsing the class index. I understand you don't want parent class headings due to clutter. I'd suggest at least putting them in a simple `title=...` so they're available on hover.

**Comment by marcelblum** [comment]
ping @tambien sorry to bother but I'd still like to take a stab at this and was hoping to get your input (answers to my Qs in my last 2 comments above) before proceeding.

**Comment by tambien** [comment]
(sorry for the delay, i was traveling for the past couple of weeks). I lean towards grouping all of the methods and properties inherited from ToneAudioNode together. Instead of adding a whole new header, i would sort by all of the properties/methods which belong to the class and it's ancestors before "ToneAudioNode" and place them at the front of the list, then put an inline header (so no line break sot they keep a compact block structure) which says "Inherited from ToneAudioNode". 

i'd also sort the results down below in the same order. And put all the other properties below a heading which says "Inherited from ToneAudioNode". I might even consider collapsing those properties a <detail> tag so the pages are a little smaller. 

If you'd like to give it a shot, i'd gladly take a look. Thanks for your interest in trying to make the docs better for everyone!

**Pull request merged**
